import * as crypto from "./libs/crypto";
import * as language from "./libs/language";
import * as response from "./libs/response";
import * as time from "./libs/time";
import * as validation from "./libs/validation";
export const libCrypto = crypto;
export const libLang = language;
export const libResp = response;
export const libTime = time;
export const libValidation = validation;
